### PR TITLE
Plugin compatibility

### PR DESCRIPTION
**Pull request by phpbits**

### CODE REVIEW

**Comment by lubieowoce** [comment]
what's "Iceberg Mode"? only thing google gave me was some theme called "Iceberg"

**Comment by phpbits** [comment]
@lubieowoce Nope, it's a plugin that me and Rich are working on right now : https://twitter.com/useiceberg. Hoping to release this next week :)

**Comment by lubieowoce** [comment]
i'm intrigued! followed+subscribed to the mailing thing. do you have a description of planned features somewhere?

**Comment by phpbits** [comment]
@lubieowoce Yeah, here's what we can share for now : https://twitter.com/richard_tabor/status/1259824183070150656 . I really hope you'll like this plugin as well!

**Pull request merged**
