### PR TITLE
Make formats work correctly when editing a reusable block

### LINKED ISSUE #277: Unable to edit blocks which are part of a reusable block
When I create a reusable block from multiple other blocks, then edit the reusable block and click on a child block to edit it, the following two errors are thrown.

(The same issue occurs when the reusable block is just a simple paragraph.)

    TypeError: Cannot read property 'filter' of undefined
    TypeError: Cannot read property 'clientId' of undefined

**To reproduce**

- Add a core/heading and core/paragraph with some simple text
- Create a group from these two blocks
- Convert the group to a reusable block.
- Edit the reusable block.
- Click on e.g. the heading to edit it.

**Expected behavior**
The text should be editable.

**Editor version**
- WordPress version **5.4**
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? **Either**

**Desktop**
 - OS: **OSX**
 - Browser **Chrome**
 - Version **81**

### PR DESCRIPTION
**Pull request by lubieowoce**
Fixes #277.

### Root cause
~~It appears that when editing a reusable block, `getSelectedBlock()` returns `null`¹, and formats that require a selected block (indent, justify, alignment) weren't properly guarding against that.~~

~~this would also make #276 worth looking at -- without something like that (or changes in gutenberg), these formats won't be available in reusable blocks.~~

I've looked at gutenberg's code, and `ReusableBlockEdit` actually instantiates a whole separate `BlockList` with its own Block Editor context, clientIds and everything. Because of this, the global `wp.data.select` doesn't work, as it operates on the global editor context, not the nested one. that's why `wp.data.select('core/block-editor').getSelectedBlock()` was returning `null` -- as far as the main editor is concerned, there really is no selected block, it's all happening in the "child" editor.

To work within the nested block editor, we have to use the `select` exposed by `withSelect((select) => ...)`, and I've updated the code accordingly in the second commit.

### Changes
- **FIX**: use the `select` provided by `withSelect((select) => ...)` instead of `wp.data.select` 
- **FIX**: If a format requires a selected block, defensively check if one is actually available and don't render it otherwise (in `ifCondition`)
- **FIX**: `props.isDisabled` was always `undefined` (and treated as `false`) if no block was selected, because the `withSelect` returned `{}`.

i've seen other uses of `wp.data.select` in the codebase that should probably be fixed too, but i didn't want to drop it all in one huge PR. the changes here are limited to the `formats/` directory.

### CODE REVIEW

**Comment by lubieowoce** [comment]
(Accidentally committed `npm start` output into `build/`, fixed now)

**Comment by lubieowoce** [comment]
i've also found a way to get rid of `updateBlockAttributes` altogether, and just use the `setAttributes` callback from `BlockEdit`: https://github.com/lubieowoce/block-options/tree/with-block-edit-props

**Comment by phpbits** [comment]
@lubieowoce My apologies for late response and thank you very much for this PR! I really appreciate your help with this issue. Thanks again!

**Comment by lubieowoce** [comment]
np! happy to help :)

**Pull request merged**
